### PR TITLE
Checkpoint 3 completed, Routing and States

### PR DESCRIPTION
**Pull request by ingrid3lias**
Hey @matstc !

I was attempting to merge this branch with the master from terminal, since it was not an assignment, and when I tried to merge with the master, an alert came up in terminal about the dist/ files:

```
error: Your local changes to the following files would be overwritten by merge:
    dist/index.html
    dist/scripts/app.js
Please, commit your changes or stash them before you can merge.
error: The following untracked working tree files would be overwritten by merge:
```

And I was wondering why that it happening? Is it because I ran `grunt` before starting on the checkpoint? Am I supposed to activate grunt before I start working so that it's always "watching" or am I supposed to do that separately/after?

Thank you!

### CODE REVIEW

**Comment by matstc** [comment]
Hi Ingrid. This is happening because you have local changes. If you run `git status` you will see them.

You should decide what to do with these local changes before you merge. If these files are "derived" files createad by grunt, then you can safely get rid of those changes with `git checkout dist` for tracked files or just `rm FILE` for untracked files. Otherwise, you would usually commit your changes before running a merge. Once your `git status` is clean, you'll be able to merge without problems.

**Comment by ingrid3lias** [comment]
hmmm..... i tried deleting them.... and then just ended up making a mess of my merges/commits. :( 

```
~/bloc/bloc-jams-angular$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

    modified:   app/pages/index.html
    modified:   app/scripts/app.js
    modified:   app/styles/landing.css
    new file:   app/templates/album.html
    new file:   app/templates/collection.html
    deleted:    app/templates/home.html
    new file:   app/templates/landing.html
    modified:   dist/scripts/app.js
    new file:   dist/templates/album.html
    new file:   dist/templates/collection.html
    deleted:    dist/templates/home.html
    new file:   dist/templates/landing.html

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

    deleted by us:   dist/index.html
    both added:      dist/styles/landing.css

~/bloc/bloc-jams-angular$ git commit
U   dist/index.html
U   dist/styles/landing.css
error: 'commit' is not possible because you have unmerged files.
hint: Fix them up in the work tree,
hint: and then use 'git add/rm <file>' as
hint: appropriate to mark resolution and make a commit,
hint: or use 'git commit -a'.
fatal: Exiting because of an unresolved conflict.
~/bloc/bloc-jams-angular$ git rm dist/index.html
dist/index.html: needs merge
rm 'dist/index.html'
~/bloc/bloc-jams-angular$ git merge
error: 'merge' is not possible because you have unmerged files.
hint: Fix them up in the work tree,
hint: and then use 'git add/rm <file>' as
hint: appropriate to mark resolution and make a commit,
hint: or use 'git commit -a'.
fatal: Exiting because of an unresolved conflict.
```

**Comment by ingrid3lias** [comment]
```
~/bloc/bloc-jams-angular$ git commit

         file name: ~ingridelias/bloc/bloc-jams-angular/.git/COMMIT_EDITMSG
          modified: YES
         user name: ingridelias   host name: Ingrids-MacBook-Air.local
        process ID: 26523
While opening file "/Users/ingridelias/bloc/bloc-jams-angular/.git/COMMIT_EDITMS
G"
             dated: Tue Dec  8 18:58:30 2015
      NEWER than swap file!

(1) Another program may be editing the same file.
    If this is the case, be careful not to end up with two
    different instances of the same file when making changes.
    Quit, or continue with caution.

(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /Users/ingridelias/bloc/bloc-
jams-angular/.git/COMMIT_EDITMSG"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/ingridelias/bloc/bloc-
jams-angular/.git/.COMMIT_EDITMSG.swp"
    to avoid this message.

Swap file "~/bloc/bloc-jams-angular/.git/.COMMIT_EDITMSG.swp" already exists!
```

I'm sending you this too to be more specific about the issue. I've googled and tried a number of different solutions and I end up with this and terminal asking me to commit.

**Comment by matstc** [comment]
Hi Ingrid—Ayay! Things have become more complicated ;)

Can you try `git merge --abort` (to cancel the merging) and then `git status`? You could paste the result of these commands here.

**Comment by ingrid3lias** [comment]
```
~/bloc/bloc-jams-angular$ git merge --abort
~/bloc/bloc-jams-angular$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
~/bloc/bloc-jams-angular$ 
```

So now that those files aren't wanting to be commited, can I try to merge this branch with the master?

**Comment by matstc** [comment]
Okay, now you can merge the `checkpoint-3-routing` branch into master.

But you will have conflicts with files `dist/index.html` and `dist/styles/landing.css`. You can just accept these files into master by running `git add .` after you merge. Then you can commit and push.

**Comment by ingrid3lias** [comment]
Hurrah! Thank you so much! That was a lot easier than all of the solutions I was looking up.

**Pull request merged**
